# Generated by Django 5.2.1 on 2025-06-01 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_customuser_apellido_customuser_comuna_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='comuna',
        ),
    ]
