# Generated by Django 5.2.1 on 2025-06-01 23:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_remove_customuser_comuna'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='comprobante_transferencia',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])]),
        ),
    ]
