# Generated by Django 5.2.1 on 2025-06-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_pedido_comprobante_transferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('bodeguero', 'Bodeguero'), ('contador', 'Contador'), ('repartidor', 'Repartidor')], default='cliente', max_length=20),
        ),
    ]
