# Generated by Django 5.2.1 on 2025-06-22 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_customuser_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
