# Generated by Django 5.2.1 on 2025-06-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_pedido_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='impuesto',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_mayorista',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_unitario',
            field=models.IntegerField(default=0),
        ),
    ]
