# Generated by Django 5.2.1 on 2025-06-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_alter_producto_impuesto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='collection_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
